#!/usr/bin/env python3
"""
How many RCS thruster failures actually cost a control DOF (Farkas' Lemma)
═════════════════════════════════════════════════════════════════════════
RCS thrusters PUSH ONLY: every throttle satisfies f_i >= 0. The achievable
wrench set is therefore the convex CONE generated by the thruster wrench
columns, not their linear span. A surviving set retains full m-DOF authority
only if its columns POSITIVELY span R^m.

By Farkas' Lemma, a set {w_i} fails to positively span R^m exactly when there
is some y != 0 with

        y . w_i  <=  0     for every surviving i

i.e. a direction no remaining thruster can push against. The vehicle can then
never command a wrench with a positive component along y, so that DOF is gone
even though the columns may still LINEARLY span R^m.

This is why counting cannot answer the question. `floor(N/k) - 1` assumes the
worst case is losing a whole cluster, but with one-sided actuators the worst
case is losing whichever few thrusters open up a halfspace - often far fewer.

MINIMUM FAILURES TO BREAK THE SPAN
----------------------------------
Removing thrusters to create such a y means removing exactly those with
y . w_i > 0. So

    n_min  =  min over y != 0 of  #{ i : y . w_i > 0 }

The count is piecewise constant in y and changes only as y crosses a plane
w_i^perp. Sliding y onto such a boundary can only move columns from the
strictly-positive side onto it, never off, so the minimum is attained where y
is orthogonal to m-1 linearly independent columns. Enumerating those (m-1)
subsets therefore gives the EXACT minimum, not a bound.

CAVEAT: the answer depends entirely on the thruster geometry, which the source
workbook does not contain. Geometry comes from Python/actuation_envelopes and
is ESTIMATED for every vehicle except the Apollo Lunar Module, whose layout is
this repository's own validated model.
"""

import sys
from itertools import combinations
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.optimize import linprog

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[1] / "src" / "apollo_gnc"))

from vehicles import build_all                                  # noqa: E402

WORKBOOK = HERE.parents[1] / "data" / "spacecraft_values.xlsx"

# Which rows of the 6-row wrench [Fx,Fy,Fz,L,M,N] the required DOF refers to.
# The tier being assessed is the ATTITUDE tier, so 3 DOF means the three
# moments; 6 DOF means full force + moment; 2 DOF (spin-stabilised MSG, Juno)
# means the two transverse axes.
DOF_ROWS = {2: [3, 4], 3: [3, 4, 5], 6: [0, 1, 2, 3, 4, 5]}


def wrench_matrix(veh):
    """6 x N wrench columns [d ; r x d] for the vehicle's RCS thrusters."""
    if not veh.rcs:
        return None
    return np.array([np.concatenate([t.dir, np.cross(t.pos, t.dir)])
                     for t in veh.rcs]).T


def positively_spans(W, tol=1e-9):
    """True if the columns of W positively span R^m (Farkas: no y with
    y.w_i <= 0 for all i)."""
    return min_failures_to_lose_span(W, tol) > 0


def min_failures_to_lose_span(W, tol=1e-9, want_depth=False):
    """Exact minimum number of column removals after which the survivors no
    longer positively span R^m. Returns 0 if they never did.

    With want_depth=True also returns how DEEP the resulting violation is:

        depth = -max over survivors of  y . w_hat_i        (columns normalised)

    depth ~ 0 means the survivors merely TOUCH the bounding hyperplane - the
    cone is degenerate but not strictly one-sided, and any small perturbation
    of the real hardware could fall either way. depth > 0 means a genuine open
    halfspace no survivor can push into. The distinction matters: a marginal
    break is a property of an idealised symmetric layout, not a robust fact.
    """
    m, N = W.shape
    if m == 0 or N == 0:
        return (0, 0.0) if want_depth else 0
    norms = np.linalg.norm(W, axis=0)
    Wh = W / np.where(norms > tol, norms, 1.0)     # compare directions fairly

    best, best_depth = N, 0.0
    for idx in combinations(range(N), m - 1) if m > 1 else [()]:
        A = Wh[:, list(idx)] if idx else np.zeros((m, 0))
        # y must be orthogonal to these m-1 columns; need them independent so
        # the orthogonal complement is a single direction
        if A.shape[1]:
            s = np.linalg.svd(A, compute_uv=False)
            if np.sum(s > tol) < m - 1:
                continue                       # degenerate subset, skipped
        _, s2, vt = np.linalg.svd(A.T if A.shape[1] else np.zeros((1, m)))
        rank = int(np.sum(s2 > tol)) if A.shape[1] else 0
        for y in vt[rank:]:
            for sgn in (1.0, -1.0):
                proj = (sgn * y) @ Wh
                cnt = int(np.sum(proj > tol))
                surv = proj[proj <= tol]
                depth = float(-surv.max()) if surv.size else 0.0
                if cnt < best or (cnt == best and depth > best_depth):
                    best, best_depth = cnt, depth
    return (best, best_depth) if want_depth else best


def spans(W, tol=1e-7):
    """Fast test: do the columns of W positively span R^m?

    Same question as min_failures_to_lose_span(W) > 0, but answered with one
    LP instead of enumerating C(N, m-1) subsets - it is called thousands of
    times by lethal_counts() below, where the enumerating version is ~85x too
    slow.

    A set positively spans R^m exactly when it LINEARLY spans R^m and the
    origin is a strictly positive combination of it: some a > 0 with W a = 0.
    (=> is Gordan's theorem, the same duality Farkas' Lemma comes from; <= is
    immediate, since any target can be reached by adding enough of the zero
    combination.) 'a >= 1' is just 'a > 0' rescaled, which makes it an LP.
    """
    m, N = W.shape
    if N < m + 1 or np.linalg.matrix_rank(W, tol) < m:
        return False
    r = linprog(np.zeros(N), A_eq=W, b_eq=np.zeros(m),
                bounds=[(1, None)] * N, method="highs")
    return r.status == 0


def lethal_counts(dof=None, max_k=4):
    """How many WAYS the vehicle can lose its control DOF to k failures.

    Returns {spacecraft: {"N": units, "m": DOF, "counts": {k: fatal k-subsets}}}
    for k = 1..max_k. Losing k thrusters is fatal for SOME choices of which k
    and survivable for others - counting the fatal choices is what turns the
    geometry into a probability, instead of assuming the worst case always.

    `dof` optionally overrides the workbook's required-DOF column per
    spacecraft; the caller decides how much the RCS is actually responsible
    for, which depends on whether a TVC engine handles translation.

    Only sets that do not already contain a smaller fatal set need testing:
    failures are monotone, so any superset of a fatal set is fatal.
    """
    vehicles = {v.name: v for v in build_all()}
    d = pd.read_excel(WORKBOOK, "Data")
    out = {}
    for _, r in d.iterrows():
        name = str(r["Spacecraft"])
        veh = vehicles.get(name)
        W = wrench_matrix(veh) if veh else None
        m = (dof or {}).get(name, r["Control DOF required, m"])
        rows = DOF_ROWS.get(int(m)) if not pd.isna(m) else None
        if W is None or W.shape[1] == 0 or rows is None:
            continue
        Wm, N = W[rows, :], W.shape[1]

        counts, fatal = {}, set()
        for k in range(1, min(max_k, N) + 1):
            found, n_fatal = set(), 0
            for c in combinations(range(N), k):
                cs = set(c)
                if any(f <= cs for f in fatal):      # superset of a fatal set
                    n_fatal += 1
                elif not spans(Wm[:, [i for i in range(N) if i not in cs]]):
                    found.add(frozenset(c))
                    n_fatal += 1
            counts[k] = n_fatal
            fatal |= found
        out[veh.name] = {"N": N, "m": len(rows), "counts": counts}
    return out


def worst_case_cluster_loss(veh, W, rows, k):
    """For reference: how many DOF survive losing one whole cluster, the case
    the floor(N/k) heuristic is built around."""
    if not k or k < 1:
        return None
    N = W.shape[1]
    per = N // int(k)
    if per < 1:
        return None
    # thrusters are generated cluster by cluster, so slice them that way
    worst = None
    for c in range(int(k)):
        keep = [i for i in range(N) if not (c * per <= i < (c + 1) * per)]
        if not keep:
            continue
        ok = min_failures_to_lose_span(W[np.ix_(rows, keep)]) > 0
        worst = ok if worst is None else (worst and ok)
    return worst


def main():
    d = pd.read_excel(WORKBOOK, "Data")
    meta = {str(r["Spacecraft"]): r for _, r in d.iterrows()}
    vehicles = {v.name: v for v in build_all()}

    out = []
    for name, r in meta.items():
        N, k, m = r["Units installed, N"], r["Actuator groups/clusters, k"], \
                  r["Control DOF required, m"]
        if pd.isna(N) or pd.isna(k) or pd.isna(m):
            continue
        veh = vehicles.get(name)
        W = wrench_matrix(veh) if veh else None
        if W is None or W.shape[1] == 0:
            continue
        rows = DOF_ROWS.get(int(m))
        if rows is None:
            continue
        Wm = W[rows, :]

        n_farkas, depth = min_failures_to_lose_span(Wm, want_depth=True)
        n_count = int(N // k)                       # what the script uses now
        spans = n_farkas > 0
        cluster_ok = worst_case_cluster_loss(veh, W, rows, k)

        out.append(dict(Spacecraft=name, N=int(N), k=int(k), m=int(m),
                        n_count=n_count, n_farkas=n_farkas,
                        depth=round(depth, 4),
                        kind=("degenerate" if n_farkas == 0 else
                              "marginal" if depth < 1e-6 else "robust"),
                        spans_intact=spans, survives_cluster_loss=cluster_ok,
                        geometry=("SOURCED" if not veh.is_estimated("rcs_layout")
                                  else "ESTIMATED")))
    df = pd.DataFrame(out)
    df["agrees"] = df["n_count"] == df["n_farkas"]
    return df


if __name__ == "__main__":
    df = main()
    pd.set_option("display.width", 200)
    print(df.to_string(index=False))
    print()
    bad = df[~df["agrees"]]
    print(f"{len(bad)} of {len(df)} disagree with the floor(N/k) heuristic")
